import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins } from '@next/font/google';
import Header from "./component/header";
import Footer from "./component/footer";

// Load the Poppins font
const poppins = Poppins({
  subsets: ['latin'], // Specify the subset you want (e.g., 'latin', 'latin-ext', etc.)
  weight: ['400', '600', '700', '800', '900'], // Choose font weights
  style: ['normal'], // Optional: Add styles (normal, italic)
});

const inter = Inter({
  subsets: ["latin"],
  weight: ['400', '600', '700', '800'],
  style: ['normal'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body className={`${inter.className}`}>
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
